### ISSUE TITLE
Error:  Call to a member function find() on boolean

### ISSUE THREAD

**Issue by rohit1290** [iionly/elggx_fivestar#5]
The following error is occurring in the Elgg Fivestar Plugin. I am using Elgg 2.3.3

```
Exception at time 1499499710: Error: Call to a member function find() on boolean in /home/domain/public_html/mod/elggx_fivestar/start.php:172 
Stack trace: 
#0 /home/domain/public_html/mod/elggx_fivestar/start.php(50): elggx_fivestar_widget('', Array, Array) 
#1 [internal function]: elggx_fivestar_view('view', 'object/album', '', Array) 
#2 /home/domain/public_html/vendor/elgg/elgg/engine/classes/Elgg/PluginHooksService.php(52): call_user_func_array('elggx_fivestar_...', Array) 
#3 /home/domain/public_html/vendor/elgg/elgg/engine/classes/Elgg/ViewsService.php(328): Elgg\PluginHooksService->trigger('view', 'object/album', Array, '') 
#4 /home/domain/public_html/vendor/elgg/elgg/engine/lib/views.php(337): Elgg\ViewsService->renderView('jssor/album_ext...', Array, false, 'rss') 
#5 /home/domain/public_html/vendor/elgg/elgg/engine/lib/views.php(905): elgg_view('object/album', Array, false, false) 
#6 /home/domain/public_html/mod/tidypics/views/default/resources/tidypics/photos/album/view.php(40): elgg_view_entity(Object(TidypicsAlbum), Array) 
#7 /home/domain/public_html/vendor/elgg/elgg/engine/classes/Elgg/ViewsService.php(370): include('/home/domain/pu...') 
#8 /home/domain/public_html/vendor/elgg/elgg/engine/classes/Elgg/ViewsService.php(306): Elgg\ViewsService->renderViewFile('resources/tidyp...', Array, 'default', true) 
#9 /home/domain/public_html/vendor/elgg/elgg/engine/lib/views.php(518): Elgg\ViewsService->renderView('resources/tidyp...', Array, false, 'default') 
#10 /home/domain/public_html/mod/tidypics/start.php(216): elgg_view_resource('tidypics/photos...', Array) 
#11 [internal function]: tidypics_page_handler(Array, 'photos') 
#12 /home/domain/public_html/vendor/elgg/elgg/engine/classes/Elgg/Router.php(100): call_user_func('tidypics_page_h...', Array, 'photos') 
#13 /home/domain/public_html/vendor/elgg/elgg/engine/classes/Elgg/Application.php(436): Elgg\Router->route(Object(Elgg\Http\Request)) 
#14 /home/domain/public_html/vendor/elgg/elgg/engine/classes/Elgg/Application.php(384): Elgg\Application->run() 
#15 /home/domain/public_html/index.php(8): Elgg\Application::index() 
#16 {main} 
```

Kindly help!

**Comment by iionly** [comment]
The find() function that appears to be missing is provided by the Elggx Fivestar plugin. So, it's quite unlikely that it's missing.

Do you have this error only with Tidypics albums (and maybe images)? Or does the same error also occur with the fivestar widgets on other type of content (e.g. blogs)? I'm asking because I see a reference to the jssor plugin (at least I think you have it installed). This jssor plugin might cause the problem, i.e. a conflict with the Fivestar plugin. The jssor plugin might not even still work without issues on newer versions of Tidypics.

My suggestion: disable the jssor plugin. Do you still see the error then? If not, it's the developer of the jssor plugin who would need to fix the problem.

**Comment by rohit1290** [comment]
Yes, I was using the jssor plugin. I have deactivated it and it solved the problem.
